blog/urls.py
from django.urls import path, include
from . import views
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView
)

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('home/', PostListView.as_view(), name='blog-home'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('about/', views.about, name='blog-about'),
]

blogproject/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('loginapp/', include('loginapp.urls', namespace='loginapp')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('admin/', admin.site.urls),
]

loginapp/urls.py
from django.urls import path, include

from . import views


app_name = 'loginapp'

urlpatterns = [
    path('', views.login, name='login'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('password_reset_confirmation/', views.password_reset_confirmation, name='password_reset_confirmation'),
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    
    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})

loginapp/models.py
from django.db import models

# Create your models here.

loginapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserSignupForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

blog/views.py
from django.shortcuts import render
from django.urls import reverse
from .models import Post
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)


# Create your views here.
def home(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'blog/home.html', context)


def about(request):
    return render(request, 'blog/about.html')


class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html' 
    context_object_name = 'posts'
    ordering = ['-date_posted']


class PostDetailView(DetailView):
    model = Post


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content']
    success_url = '/blog/'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']
    success_url = '/blog/'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/blog/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

loginapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
from django.contrib import messages
from .forms import UserSignupForm
from django.contrib.auth.decorators import login_required


def login(request):
    context = {}
    if request.method == 'POST':
        user = authenticate(request, 
            username=request.POST['user'], 
            password=request.POST['password'])
        if user:
            dj_login(request, user)
            context = {'user':request.POST['user']}
            return HttpResponseRedirect(reverse('loginapp:profile'))
        else:
            context = {'error':'Username or password is wrong.'}

    return render(request, 'loginapp/login.html', context)

def logout(request):
    dj_logout(request)
    return HttpResponseRedirect(reverse('loginapp:login'))

@login_required
def profile(request):    
    return render(request, 'loginapp/profile.html')

def signup(request):
    if request.method == 'POST':
        form = UserSignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for { username }!')
            return HttpResponseRedirect(reverse('loginapp:login'))
    else:
        form = UserSignupForm()
    return render(request,'loginapp/signup.html', {'form':form})


def password_reset(request):
    context = {}
    if request.method == 'POST':
        users = User.objects.filter(username=request.POST['user'])
        if users:
            user = users[0]
            new_password = random_string()
            #new_password = '1111'
            user.set_password(new_password)
            user.save()
            print(f'**** User {user} changed password to {new_password}')
            return HttpResponseRedirect(reverse('loginapp:password_reset_confirmation'))
        else:
            context['error'] = 'No such username.'
        
    return render(request, 'loginapp/password_reset.html', context)

def password_reset_confirmation(request):    
    return render(request, 'loginapp/password_reset_confirmation.html')

blog/templates/blog/about.html
{% extends 'blog/base.html ' %}
{% block content %}
    <div class="content-section">
        <h1>About this blog</h1>
    </div>
{% endblock content %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">

    <title>Document</title>
</head>
<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'blog:blog-home' %}">Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{% url 'blog:blog-home' %}">Home</a>
                    <a class="nav-item nav-link" href="{% url 'blog:blog-about' %}">About</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'blog:post-create' %}">New Post</a>
                        <a class="nav-item nav-link" href="{% url 'loginapp:profile' %}">Profile</a>
                        <a class="nav-item nav-link" href="{% url 'loginapp:logout' %}">Logout</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{% url 'loginapp:login' %}">Login</a>
                        <a class="nav-item nav-link" href="{% url 'loginapp:signup' %}">Sign Up</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>
<main role="main" class="container">
    <div class="row">
        <div class="col-md-12">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</main>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

</body>
</html>

blog/templates/blog/home.html
{% extends 'blog/base.html ' %}
{% block content %}
    {% for post in posts %}

        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <small class="text-muted">Posted by <a class="mr-2" href="#">{{ post.author }}</a></small>
                    <small class="text-muted">on {{ post.date_posted|date:"d-m-Y, H:i" }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'blog:post-detail' post.id %}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>

    {% endfor %}
{% endblock content %}

blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}


    <div class="content-section">
        <form method="POST">
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                {% csrf_token %}

                <h2>Confirm delete?</h2>
                <br/>
            </fieldset>
            <div class="form-group">
                <input type="submit" class="btn btn-danger" value="Delete">
                <a class="btn btn-secondary" href="{% url 'blog:post-detail' object.id %}">Cancel</a>
            </div>
        </form>


        {% if error %}<p class="error">{{ error }}</p>{% endif %}


    </div>

{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html ' %}
{% block content %}


    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <small class="text-muted">Posted by <a class="mr-2" href="#">{{ object.author }}</a></small>
                <small class="text-muted">on {{ object.date_posted|date:"d-m-Y, H:i" }}</small>
                {% if object.author == user %}
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1"
                           href="{% url 'blog:post-update' object.id %}">Edit</a>
                        <a class="btn btn-danger btn-sm mt-1 mb-1"
                           href="{% url 'blog:post-delete' object.id %}">Delete</a>
                    </div>
                {% endif %}
            </div>
            <h2 class="article-title">{{ object.title }}</h2>
            <p class="article-content">{{ object.content }}</p>
        </div>
    </article>







{% endblock content %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}


    <div class="content-section">
        <form method="POST">
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                {% csrf_token %}

                {{ form|crispy }}
                <br/>
            </fieldset>
            <div class="form-group">
                <input type="submit" class="btn btn-info" value="Post">
            </div>
        </form>


        {% if error %}<p class="error">{{ error }}</p>{% endif %}


    </div>

{% endblock content %}

loginapp/templates/loginapp/login.html
{% extends "blog/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}


    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}


    <div class="container">
        <div class="content-section">
            <form action="." method="POST">
                <fieldset class="form-group">

                    <legend class="border-bottom mb-4">Log In</legend>
                    {% csrf_token %}
                    <label for="user">Username</label>
                    <br/>
                    <input type="text" class="form-control" id="user" name="user" placeholder="User Name">
                    <br/>
                    <label for="password">Password</label>
                    <br/>
                    <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                    <br/>
                </fieldset>
                <div class="form-group">
                    <input type="submit" class="btn btn-info" value="Log In">
                </div>
            </form>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Don't Have An Account Yet? <a class="ml-2" href="signup">Sign Up</a>
                </small>
            </div>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Forgot Password? <a class="ml-2" href="{% url 'loginapp:password_reset' %}">Reset It Here</a>
                </small>
            </div>
        </div>
    </div>
    {% if error %}<p class="error">{{ error }}</p>{% endif %}

{% endblock content %}

loginapp/templates/loginapp/password_reset.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="container">
        <div class="content-section">


            <form action="{% url 'loginapp:password_reset' %}" method="POST">
                {% csrf_token %}
                <fieldset class="form-group">

                    <legend class="border-bottom mb-4">Password reset</legend>
                    <label for="user">Enter your username</label>
                    <input type="text" class="form-control" id="user" name="user" placeholder="User Name">
                </fieldset>
                <div class="form-group">
                    <input type="submit" class="btn btn-danger" value="Reset password">
                </div>
            </form>

        </div>
    </div>
    {% if error %}
        <p class="error">{{ error }}</p>
    {% endif %}
{% endblock content %}

loginapp/templates/loginapp/password_reset_confirmation.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="alert alert-info">
        Your password has been reset. You can now<a class="ml-2" href="{% url 'loginapp:login' %}">log in</a> with the
        new one.
    </div>
{% endblock content %}

loginapp/templates/loginapp/profile.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <div class="media">

            <div class="media-body">
                <h2 class="account-heading">{{ user.username }}'s profile</h2>
                <p class="text-secondary">Email: {{ user.email }}</p>
            </div>
        </div>

    </div>
{% endblock content %}

loginapp/templates/loginapp/signup.html
{% extends "blog/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="container">
        <div class="content-section">
            <form method="POST">
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Sign Up</legend>
                    {% csrf_token %}

                    {{ form|crispy }}
                    <br/>
                </fieldset>
                <div class="form-group">
                    <input type="submit" class="btn btn-info" value="Sign Up">
                </div>
            </form>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Already Have An Account? <a class="ml-2" href="login">Log In</a>
                </small>
            </div>
        </div>
        {% if error %}<p class="error">{{ error }}</p>{% endif %}


    </div>

{% endblock content %}